import type { CityDiscoveryItem } from './cityDiscoveryEngine.ts';

export const cityDiscoveryDemoCatalog:CityDiscoveryItem[]=[
  {
    id:'demo-museum-evening',
    kind:'museum',
    district:'Хамовники',
    titleRu:'Вечерний музейный слот',
    titleEn:'Evening museum slot',
    titleZh:'晚间博物馆时段',
    startsAt:'2026-10-07T18:00:00+03:00',
    endsAt:'2026-10-07T20:00:00+03:00',
    durationMinutes:90,
    latitude:55.744,
    longitude:37.591,
    tags:['culture','evening','museum'],
    truth:'demo',
    availability:'available',
    availabilityTruth:'demo',
    qualityScore:4.7
  },
  {
    id:'demo-theatre-tonight',
    kind:'theatre',
    district:'Тверской',
    titleRu:'Театр сегодня вечером',
    titleEn:'Theatre tonight',
    titleZh:'今晚剧院',
    startsAt:'2026-10-07T19:30:00+03:00',
    endsAt:'2026-10-07T22:00:00+03:00',
    durationMinutes:150,
    latitude:55.765,
    longitude:37.61,
    tags:['culture','theatre','evening'],
    truth:'demo',
    availability:'limited',
    availabilityTruth:'demo',
    qualityScore:4.8
  },
  {
    id:'demo-basmanny-exhibition',
    kind:'exhibition',
    district:'Басманный',
    titleRu:'Современная выставка в Басманном',
    titleEn:'Contemporary exhibition in Basmanny',
    titleZh:'巴斯曼区当代展览',
    startsAt:'2026-10-07T12:00:00+03:00',
    endsAt:'2026-10-07T21:00:00+03:00',
    durationMinutes:75,
    latitude:55.763,
    longitude:37.66,
    tags:['art','new-district','indoor'],
    truth:'demo',
    availability:'available',
    availabilityTruth:'demo',
    qualityScore:4.6
  },
  {
    id:'demo-zamoskvorechye-dinner',
    kind:'restaurant',
    district:'Замоскворечье',
    titleRu:'Ужин после культурного блока',
    titleEn:'Dinner after culture',
    titleZh:'文化活动后的晚餐',
    durationMinutes:90,
    latitude:55.736,
    longitude:37.625,
    tags:['food','evening','dinner'],
    truth:'demo',
    availability:'available',
    availabilityTruth:'demo',
    qualityScore:4.5
  },
  {
    id:'demo-presnya-event',
    kind:'concert',
    district:'Пресненский',
    titleRu:'Концерт как якорь вечернего маршрута',
    titleEn:'Concert as an evening anchor',
    titleZh:'作为夜间行程锚点的音乐会',
    startsAt:'2026-10-07T20:00:00+03:00',
    endsAt:'2026-10-07T22:30:00+03:00',
    durationMinutes:150,
    latitude:55.755,
    longitude:37.558,
    tags:['music','event','night'],
    truth:'demo',
    availability:'available',
    availabilityTruth:'demo',
    qualityScore:4.4
  },
  {
    id:'demo-vdnh-family',
    kind:'family',
    district:'Останкинский / ВДНХ',
    titleRu:'Семейный дневной кластер',
    titleEn:'Family daytime cluster',
    titleZh:'家庭白日体验集群',
    durationMinutes:240,
    latitude:55.829,
    longitude:37.633,
    tags:['family','half-day','park'],
    truth:'demo',
    availability:'unknown',
    availabilityTruth:'unknown',
    qualityScore:4.6
  },
  {
    id:'demo-gorky-park',
    kind:'park',
    district:'Якиманка',
    titleRu:'Парк и прогулка у воды',
    titleEn:'Park and riverside walk',
    titleZh:'公园与河畔漫步',
    durationMinutes:90,
    latitude:55.729,
    longitude:37.601,
    tags:['outdoor','walk','park'],
    truth:'demo',
    availability:'available',
    availabilityTruth:'demo',
    qualityScore:4.5
  },
  {
    id:'demo-nightlife-khitrovka',
    kind:'bar',
    district:'Басманный',
    titleRu:'Продолжить вечер в баре',
    titleEn:'Continue the evening at a bar',
    titleZh:'酒吧续摊',
    startsAt:'2026-10-07T21:00:00+03:00',
    endsAt:'2026-10-08T02:00:00+03:00',
    durationMinutes:120,
    latitude:55.755,
    longitude:37.646,
    tags:['nightlife','late','bar'],
    truth:'demo',
    availability:'available',
    availabilityTruth:'demo',
    qualityScore:4.3
  },
  {
    id:'demo-market-shopping',
    kind:'shopping',
    district:'Даниловский',
    titleRu:'Гастромаркет и покупки',
    titleEn:'Food market and shopping',
    titleZh:'美食市集与购物',
    durationMinutes:75,
    latitude:55.711,
    longitude:37.622,
    tags:['market','food','shopping'],
    truth:'demo',
    availability:'available',
    availabilityTruth:'demo',
    qualityScore:4.4
  },
  {
    id:'demo-sponsored-evening',
    kind:'restaurant',
    district:'Арбат',
    titleRu:'Партнёрское предложение на ужин',
    titleEn:'Sponsored dinner offer',
    titleZh:'赞助晚餐推荐',
    durationMinutes:90,
    latitude:55.749,
    longitude:37.589,
    tags:['food','offer'],
    truth:'demo',
    availability:'available',
    availabilityTruth:'demo',
    qualityScore:4.7,
    sponsored:true
  }
];
